Repository redhat-beyond/Smarticle, pull requests merged in 2023-01, with the labels that each got.

#70 Adding create-article-feature
  finalProject_g4/settings.py
  finalProject_g4/urls.py
  projboard/forms.py
  projboard/static/css/404.css
  projboard/static/css/article.css
  projboard/templates/404.html
  projboard/templates/article/article.html
  projboard/templates/base.html
  projboard/tests/test_client.py
  projboard/tests/test_create_article.py
  projboard/views.py
Labels: enhancement, Ready for review

#73 Move board.html content to about page
  finalProject_g4/urls.py
  projboard/templates/about/about.html
  projboard/templates/base.html
  projboard/templates/landing/homepage.html
  projboard/tests/test_client.py
  projboard/views.py
Labels: documentation, Ready for review

#80 Inserting a real data to the Database
  finalProject_g4/settings.py
  projboard/migrations/0004_test_user_data.py
  projboard/migrations/0005_test_article_data.py
  projboard/migrations/0006_test_subject_data.py
  projboard/migrations/data/__init__.py
  projboard/migrations/data/articles_content.py
Labels: type: data

#79 Updating homepage.html file
  projboard/static/css/base.css
  projboard/static/css/homepage.css
  projboard/static/images/animated.gif
  projboard/static/images/community.png
  projboard/static/images/grow-community.png
  projboard/static/images/join-us.png
  projboard/static/images/post-article.png
  projboard/templates/landing/homepage.html
  projboard/tests/conftest.py
  projboard/tests/test_client.py
  projboard/views.py
Labels: type: documentation, Ready for review

#97 Adding search by user & subject feature
  projboard/static/css/search_article.css
  projboard/templates/searchArticle/search_article.html
  projboard/tests/test_client.py
  projboard/views.py
Labels: type: enhancement, Ready for review

#94 Creating signup feature
  finalProject_g4/urls.py
  projboard/forms.py
  projboard/static/css/base.css
  projboard/static/css/signup.css
  projboard/templates/base.html
  projboard/templates/landing/homepage.html
  projboard/templates/signup/signup.html
  projboard/tests/conftest.py
  projboard/tests/test_client.py
  projboard/tests/test_signup.py
  projboard/views.py
Labels: type: documentation, Ready for review

#99 Fixing create_article view
  projboard/tests/test_client.py
  projboard/views.py
Labels: type: bug, Ready for review

#88 Adding read article feature, adding a new view, new template, new route
  finalProject_g4/urls.py
  projboard/static/css/read_article.css
  projboard/templates/base.html
  projboard/templates/searchArticle/search_article.html
  projboard/templates/show/read_article.html
  projboard/tests/conftest.py
  projboard/tests/test_client.py
  projboard/views.py
Labels: Ready for review

#102 Linking the View Blog button
  projboard/templates/landing/homepage.html
Labels: Ready for review

#90 Adding Login feature file
  finalProject_g4/settings.py
  finalProject_g4/urls.py
  projboard/forms.py
  projboard/migrations/0004_test_user_data.py
  projboard/migrations/0009_user_user1.py
  projboard/models/user.py
  projboard/signals.py
  projboard/static/css/login.css
  projboard/templates/base.html
  projboard/templates/landing/homepage.html
  projboard/templates/login/login.html
  projboard/templates/show/read_article.html
  projboard/templates/signup/signup.html
  projboard/tests/conftest.py
  projboard/tests/test_client.py
  projboard/tests/test_login.py
  projboard/tests/test_signup.py
  projboard/views.py
Labels: Ready for review

#104 Adding demo4 Presentation
  documentations/demo4/Demo4 Presentation.pptx
Labels: type: documentation
